export const PROJECTS: Project[] = [
  {
    url: "https://lilypad.bleebo.dev",
    image_src: "/lilypad.png",
    description: "Personal finance app.",
    title: "Lilypad Finance",
    slug: "lilypad",
    categories: ["TypeScript", "React"],
  },
  {
    github_url: "https://github.com/reeceyang/symsic",
    image_src: "/symsic.png",
    description: "Fast symbolic music search engine.",
    title: "symsic",
    slug: "symsic",
    categories: ["TypeScript", "React"],
  },
  {
    github_url: "https://github.com/reeceyang/bleebo",
    description: "Personal static website publishing from the command line.",
    title: "bleebo",
    slug: "bleebo",
    categories: ["Rust"],
  },
  {
    url: "https://raytracer.bleebo.dev/",
    github_url: "https://github.com/reeceyang/rust-raytracer",
    image_src: "/raytracer.png",
    description:
      "A raytracer you can walk around in. Compiled to WASM and hosted on bleebo!",
    title: "raytracer",
    slug: "raytracer",
    categories: ["Rust"],
  },
  {
    url: "https://bobaboss.reeceyang.xyz",
    github_url: "https://github.com/reeceyang/bobaboss",
    image_src: "/bobaboss_home.png",
    description:
      "Find the best boba in Boston! Review aggregation web app that lets you explore individual boba flavors across different shops.",
    title: "BobaBoss",
    slug: "bobaboss",
    categories: ["React", "MongoDB", "Express"],
  },
  {
    url: "https://kai.bleebo.dev",
    image_src: "/kai.png",
    description: "Personal website I designed for a friend.",
    title: "Kai",
    slug: "kai",
    categories: ["JavaScript", "HTML", "CSS"],
  },
  {
    url: "https://beaverlens.reeceyang.xyz",
    image_src: "/beaverlens_home.png",
    github_url: "https://github.com/reeceyang/beaverlens",
    description:
      "Browse an archive of over 5,000 MIT Confessions through text search.",
    title: "Beaver Lens",
    slug: "beaverlens",
    categories: ["Next.js", "MongoDB", "React"],
  },
  {
    url: "https://news.convex.dev/product-update-volume-2/#schema-diagrams",
    image_src: "/convex-schema-mermaid.png",
    github_url: "https://github.com/reeceyang/convex-schema-mermaid",
    description:
      "NPM package for generating Mermaid diagrams from Convex schemas.",
    title: "convex-schema-mermaid",
    slug: "convex-schema-mermaid",
    categories: ["TypeScript"],
  },
  {
    url: "https://alixii.itch.io/flowfield",
    image_src: "/flowfield.png",
    github_url: "https://github.com/reeceyang/flowfield",
    description: "physics-based action game",
    title: "flowfield",
    slug: "flowfield",
    categories: ["Rust"],
  },
  {
    url: "https://convoscope.media.mit.edu/",
    image_src: "/convoscope.png",
    github_url: "https://github.com/TeamOpenSmartGlasses/AugmentOS",
    description: "Conversation assistant tool used at the MIT Media Lab.",
    title: "Convoscope Web Frontend",
    slug: "convoscope",
    categories: ["React"],
  },
  {
    url: "https://thehotchkissrecord.github.io/henry-web/",
    github_url: "https://github.com/TheHotchkissRecord/henry-web",
    image_src: "/henry.png",
    description:
      "A web app for building MJML email newsletters for The Hotchkiss Record, my high school’s newspaper.",
    title: "Henry",
    slug: "henry",
    categories: ["JavaScript", "MJML"],
  },
  {
    title: "Flicker",
    github_url: "https://github.com/reeceyang/flicker",
    image_src: "/flicker.png",
    slug: "flicker",
    description: "Audio plug-in that creates a flickering effect.",
    categories: ["C++", "DSP"],
  },
  {
    title: "sakura-timer",
    url: "https://reeceyang.github.io/sakura-timer/",
    image_src: "/sakura-timer.png",
    github_url: "https://github.com/reeceyang/sakura-timer",
    description: "A super minimal pomodoro timer for your browser tab bar.",
    slug: "sakura-timer",
    categories: ["JavaScript"],
  },
  {
    title: "sakura-discord",
    github_url: "https://github.com/reeceyang/sakura-discord",
    image_src: "/sakura-discord.png",
    description: "A Discord bot port of sakura-timer.",
    slug: "sakura-discord",
    categories: ["JavaScript", "Node.js"],
  },
  {
    title: "Beaver Lens Discord bot",
    url: "https://discord.com/oauth2/authorize?client_id=972229072128204861&permissions=0&scope=bot",
    github_url: "https://github.com/reeceyang/beaverlens-bot",
    description: "A bot that forwards new MIT Confessions posts to Discord.",
    image_src: "/beaverlens-discord.png",
    slug: "beaverlens-discord",
    categories: ["Rust"],
  },
  {
    title: "ecopaths",
    url: "https://reeceyang.github.io/ecopaths/",
    github_url: "https://github.com/reeceyang/ecopaths",
    image_src: "/ecopaths.png",
    description:
      "Make sustainable transportation choices for your next trip by comparing carbon emissions.",
    categories: ["JavaScript"],
    slug: "ecopaths",
  },
  {
    title: "Webscripter",
    url: "https://reeceyang.github.io/webscripter/",
    github_url: "https://github.com/reeceyang/webscripter",
    image_src: "/webscripter.png",
    description:
      "A JavaScript sandbox using Webconsole that allows users to share their code as an URL.",
    categories: ["JavaScript"],
    slug: "webscripter",
  },
  {
    title: "Webconsole",
    github_url: "https://github.com/reeceyang/webconsole",
    description:
      "A library providing a web console with print and input functions for JavaScript.",
    categories: ["JavaScript"],
    slug: "webconsole",
  },
  {
    title: "tetris.py",
    github_url: "https://github.com/reeceyang/tetris",
    image_src: "/tetris.png",
    description: "Tetris in the terminal with Python",
    categories: ["Python"],
    slug: "tetris",
  },
  {
    title: "MPC website",
    url: "https://mpc.mit.edu/",
    github_url: "https://github.com/reeceyang/mpc",
    image_src: "/mpc.png",
    description: "Website for the MIT Music Production Collaborative.",
    categories: ["Jekyll"],
    slug: "mpc",
  },
  {
    title: "expo-router-convex-auth",
    url: "https://expo-router-convex-auth.vercel.app",
    github_url: "https://github.com/reeceyang/expo-router-convex-auth",
    image_src: "/expo-router-convex-auth.png",
    description: "Expo Router and Convex Auth example",
    categories: ["TypeScript", "React"],
    slug: "expo-router-convex-auth",
  },
  {
    title: "two-word language translator",
    url: "https://reeceyang.github.io/two-word-translator/",
    github_url: "https://github.com/reeceyang/two-word-translator",
    image_src: "/two-word-demo.gif",
    description: "Invent your own two-word language!",
    categories: ["JavaScript"],
    slug: "two-word-translator",
  },
  {
    title: "The Useless Dictionary",
    url: "https://reeceyang.github.io/useless-dictionary/",
    github_url: "https://github.com/reeceyang/useless-dictionary",
    image_src: "/useless-dictionary-demo.gif",
    description:
      "Define all the words that exist, and all the words that don’t exist.",
    categories: ["JavaScript"],
    slug: "useless-dictionary",
  },
  {
    title: "Christmas Eve",
    url: "https://reeceyang.github.io/christmas-eve/",
    github_url: "https://github.com/reeceyang/christmas-eve",
    image_src: "/christmas-eve.png",
    description: "How many days are left until Christmas?",
    categories: ["JavaScript"],
    slug: "christmas-eve",
  },
  {
    title: "s",
    github_url: "https://github.com/reeceyang/s",
    description: "A simple link shortener",
    categories: ["JavaScript"],
    slug: "s",
  },
  {
    title: "luce.css",
    github_url: "https://github.com/reeceyang/luce.css",
    description: "A lightweight CSS library inspired by Henry’s design",
    categories: ["CSS"],
    slug: "luce-css",
  },
  {
    title: "Hotchkiss Tier",
    url: "https://hotchkiss-tier.vercel.app/",
    github_url: "https://hotchkiss-tier.vercel.app/",
    description: "Tier rank Hotchkiss classes.",
    slug: "hotchkiss-tier",
    categories: ["Next.js", "JavaScript", "React"],
  },
  {
    title: "randomkey",
    url: "https://reeceyang.github.io/randomkey/",
    github_url: "https://github.com/reeceyang/randomkey",
    description: "Get a random musical key.",
    categories: ["JavaScript"],
    slug: "randomkey",
  },
  {
    title: "Iowa City Math Circle",
    url: "http://iowacitymathcircle.org/",
    description:
      "28 handouts that I co-wrote for the Summer Math Circle’s weekly meeting curriculum.",
    categories: [],
    slug: "iowacitymathcircle",
  },
];
