export const PROJECTS: Project[] = [
  {
    url: "https://bobaboss.reeceyang.xyz",
    github_url: "https://github.com/reeceyang/bobaboss",
    image_src: "/bobaboss_home.png",
    description:
      "Find the best boba in Boston! Review aggregation web app that lets you explore individual boba flavors across different shops.",
    title: "BobaBoss",
    slug: "bobaboss",
    categories: ["React", "MongoDB", "Express"],
  },
  {
    url: "https://beaverlens.reeceyang.xyz",
    image_src: "/beaverlens_home.png",
    github_url: "https://github.com/reeceyang/beaverlens",
    description:
      "Browse an archive of over 5,000 MIT Confessions through text search.",
    title: "Beaver Lens",
    slug: "beaverlens",
    categories: ["Next.js", "MongoDB", "React"],
  },
  {
    url: "https://thehotchkissrecord.github.io/henry-web/",
    github_url: "https://github.com/TheHotchkissRecord/henry-web",
    image_src: "/henry.png",
    description:
      "A web app for building MJML email newsletters for The Hotchkiss Record, my high school’s newspaper.",
    title: "Henry",
    slug: "henry",
    categories: ["JavaScript", "MJML"],
  },
  {
    title: "Flicker",
    github_url: "https://github.com/reeceyang/flicker",
    image_src: "/flicker.png",
    slug: "flicker",
    description: "Audio plug-in that creates a flickering effect.",
    categories: ["C++", "DSP"],
  },
  {
    title: "sakura-timer",
    url: "https://reeceyang.github.io/sakura-timer/",
    image_src: "/sakura-timer.png",
    github_url: "https://github.com/reeceyang/sakura-timer",
    description: "A super minimal pomodoro timer for your browser tab bar.",
    slug: "sakura-timer",
    categories: ["JavaScript"],
  },
  {
    title: "sakura-discord",
    github_url: "https://github.com/reeceyang/sakura-discord",
    image_src: "/sakura-discord.png",
    description: "A Discord bot port of sakura-timer.",
    slug: "sakura-discord",
    categories: ["JavaScript", "Node.js"],
  },
  {
    title: "Beaver Lens Discord bot",
    url: "https://discord.com/oauth2/authorize?client_id=972229072128204861&permissions=0&scope=bot",
    github_url: "https://github.com/reeceyang/mitconfessionsbot",
    description: "A bot that forwards new MIT Confessions posts to Discord.",
    image_src: "/beaverlens-discord.png",
    slug: "beaverlens-discord",
    categories: ["Python", "MongoDB"]
  },
  {
    title: "ecopaths",
    url: "https://reeceyang.github.io/ecopaths/",
    github_url: "https://github.com/reeceyang/ecopaths",
    image_src: "/ecopaths.png",
    description:
      "Make sustainable transportation choices for your next trip by comparing carbon emissions.",
    categories: ["JavaScript"],
    slug: "ecopaths",
  },
  {
    title: "Webscripter",
    url: "https://reeceyang.github.io/webscripter/",
    github_url: "https://github.com/reeceyang/webscripter",
    image_src: "/webscripter.png",
    description:
      "A JavaScript sandbox using Webconsole that allows users to share their code as an URL.",
    categories: ["JavaScript"],
    slug: "webscripter",
  },
  {
    title: "Webconsole",
    github_url: "https://github.com/reeceyang/webconsole",
    description:
      "A library providing a web console with print and input functions for JavaScript.",
    categories: ["JavaScript"],
    slug: "webconsole",
  },
  {
    title: "two-word language translator",
    url: "https://reeceyang.github.io/two-word-translator/",
    github_url: "https://github.com/reeceyang/two-word-translator",
    image_src: "/two-word-demo.gif",
    description: "Invent your own two-word language!",
    categories: ["JavaScript"],
    slug: "two-word-translator",
  },
  {
    title: "The Useless Dictionary",
    url: "https://reeceyang.github.io/useless-dictionary/",
    github_url: "https://github.com/reeceyang/useless-dictionary",
    image_src: "/useless-dictionary-demo.gif",
    description:
      "Define all the words that exist, and all the words that don’t exist.",
    categories: ["JavaScript"],
    slug: "useless-dictionary",
  },
  {
    title: "Christmas Eve",
    url: "https://reeceyang.github.io/christmas-eve/",
    github_url: "https://github.com/reeceyang/christmas-eve",
    image_src: "/christmas-eve.png",
    description: "How many days are left until Christmas?",
    categories: ["JavaScript"],
    slug: "christmas-eve",
  },
  {
    title: "s",
    github_url: "https://github.com/reeceyang/s",
    description: "A simple link shortener",
    categories: ["JavaScript"],
    slug: "s",
  },
  {
    title: "luce.css",
    github_url: "https://github.com/reeceyang/luce.css",
    description: "A lightweight CSS library inspired by Henry’s design",
    categories: ["CSS"],
    slug: "luce-css",
  },
  {
    title: "Hotchkiss Tier",
    url: "https://hotchkiss-tier.vercel.app/",
    github_url: "https://hotchkiss-tier.vercel.app/",
    description: "Tier rank Hotchkiss classes.",
    slug: "hotchkiss-tier",
    categories: ["Next.js", "JavaScript", "React"],
  },
  {
    title: "randomkey",
    url: "https://reeceyang.github.io/randomkey/",
    github_url: "https://github.com/reeceyang/randomkey",
    description: "Get a random musical key.",
    categories: ["JavaScript"],
    slug: "randomkey",
  },
  {
    title: "habits & mood",
    url: "https://www.notion.so/2030b3adcbc147a4a83061d17a40adf1?v=28f005d0306e4bf68336de4bfccafa5c",
    description: "Notion template for habit and mood tracking",
    categories: [],
    slug: "habits-and-mood",
  },
  {
    title: "Iowa City Math Circle",
    url: "http://iowacitymathcircle.org/",
    description:
      "28 handouts that I co-wrote for the Summer Math Circle’s weekly meeting curriculum.",
    categories: [],
    slug: "iowacitymathcircle",
  },
];